.github/workflows/ci-cd.yml

배포 알림을 전송하는 부분을 Slack에서 Discord로 변경함.
This closes #2

배포 알림 방식을 슬랙에서 디스코드로 변경하기 위해 CI/CD 스크립트 수정

---

src/main/java/site/dogether/auth/infrastructure/client/apple/AppleApiClient.java

- apple refresh Token 요청의 응답 코드 로깅 추가

[BE] 애플 로그인 revoke 요청이 실패하는 오류 수정 3

---

src/main/java/site/dogether/auth/infrastructure/client/apple/AppleApiClient.java

- apple refresh token 요청을 request body가 아닌 params로 요청하도록 수정

[BE] 애플 로그인 revoke 요청이 실패하는 오류 수정 4

---

src/main/java/site/dogether/challengegroup/repository/ChallengeGroupMemberRepository.java
src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java

같은 그룹 중복 참여가 가능한 오류가 발견되어 이미 참여한 그룹인지 검사 로직을 추가합니다.

[BE] 같은 그룹 중복 참여 오류 수정

---

src/main/java/site/dogether/auth/service/AuthService.java
src/main/java/site/dogether/member/entity/Member.java
src/test/java/site/dogether/docs/dailytodo/DailyTodoControllerDocsTest.java

회원 객체에 회원 프로필 이미지 url 필드를 추가하여 테이블 컬럼 추가를 반영함.
This closes #38

[BE] member 테이블 프로필 이미지 url 컬럼 추가 반영

---

src/main/java/site/dogether/challengegroup/entity/ChallengeGroup.java
src/test/java/site/dogether/challengegroup/entity/ChallengeGroupDurationOptionTest.java
src/test/java/site/dogether/challengegroup/entity/ChallengeGroupStartAtOptionTest.java
src/test/java/site/dogether/challengegroup/entity/ChallengeGroupTest.java

- 챌린지 그룹 (ChallengeGroup) 테스트 코드 추가
- 챌린지 그룹 시작 옵션 (ChallengeGroupStartAtOption) 테스트 코드 추가
- 챌린지 그룹 기간 옵션 (ChallengeGroupDurationOption) 테스트 코드 추가
issue: #69

[BE] 챌린지 그룹 도메인 모델 테스트 추가

---

src/main/java/site/dogether/memberactivity/exception/InvalidParameterException.java
src/main/java/site/dogether/memberactivity/service/MemberActivityService.java

exception 패키지 내부로 들어갈 수 있도록 클래스 위치 수정하였습니다.
This closes #65

[BE] 사용자의 활동 통계 및 작성한 인증 목록 전체 조회 api 구현

---

src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
src/main/java/site/dogether/member/service/MemberService.java
src/main/java/site/dogether/memberactivity/entity/DailyTodoStats.java
src/main/java/site/dogether/memberactivity/service/MemberActivityService.java
src/main/java/site/dogether/notification/service/NotificationService.java

회원이 신규 로그인 시 memberActivityStats 테이블 내부에 등록되도록 수정하였습니다.
This closes #83

[BE] 투두 상태 변경 시 사용자 별 데일리 투두 통계 값 변경 기능 추가

---

src/main/java/site/dogether/challengegroup/entity/ChallengeGroup.java
src/main/java/site/dogether/challengegroup/repository/ChallengeGroupMemberRepository.java
src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
src/test/java/site/dogether/challengegroup/entity/ChallengeGroupTest.java
src/test/java/site/dogether/challengegroup/service/ChallengeGroupServiceTest.java

ChallengeGroupService 테스트 코드를 작성합니다.
작성한 메서드 목록
- createChallengeGroup
- joinChallengeGroup
- getJoiningChallengeGroups
- leaveChallengeGroup
- isParticipatingChallengeGroup

[BE] 챌린지 그룹 서비스 테스트 코드 추가

---

src/main/java/site/dogether/member/entity/Member.java

member의 연관 테이블에 대해 CascadeType.REMOVE를 추가합니다.

[BE] 추가된 연관 테이블 cascade 추가

---

.github/workflows/ci-cd.yml

애플리케이션 실행 체크 로직을 애플리케이션 실행 step에 포함되도록 ci-cd script를 변경했습니다.
This closes #95

chore: #95 애플리케이션 실행 체크 로직을 애플리케이션 실행 step에 포함

---

.github/workflows/ci-cd.yml

배포 스크립트를 살짝 수정했습니다.
This closes #95

ci-cd 스크립트 수정

---

.github/workflows/ci-cd.yml
src/main/java/site/dogether/common/controller/CommonController.java

chore: #95 ci-cd 스크립트 수정

---

src/main/java/site/dogether/dailytodocertification/service/DailyTodoCertificationService.java

데일리 투두 인증 오류를 해결함.
This closes #129

[BE] 데일리 투두 인증 오류 해결

---

.github/workflows/ci-cd.yml
src/main/java/site/dogether/common/controller/CommonController.java
src/main/java/site/dogether/notification/firebase/config/FirebaseConfig.java
src/main/resources/application-prod.yml
src/main/resources/logback/logback-prod.xml

운영 환경 배포 테스트

---

src/main/java/site/dogether/dailytodo/entity/DailyTodo.java
src/main/java/site/dogether/dailytodocertification/entity/DailyTodoCertification.java

Resolves #147
- 데일리 투두 내용
- 데일리 투두 인증 본문
- 인증 검사 피드백
해당 3가지 컬럼 길이 업데이트 완료(개발 db도 업데이트 작업 완료)
X

DB 컬럼 크기 변경

---

src/main/java/site/dogether/challengegroup/entity/AchievementRateCalculator.java
src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
src/test/java/site/dogether/challengegroup/entity/AchievementRateCalculatorTest.java

Resolves #150
- 더 많이 투두를 작성한 사람, 더 많이 투두를 인증한 사람, 더 많이 투두를 인정받은 사람, 더 오랜 기간 꾸준히 투두를 작성한 사람이 랭킹 순위가 높아질 수 있도록 알고리즘 수정
- 랭킹 알고리즘 테스트 코드 작성
X

랭킹 계산 알고리즘 수정

---

src/docs/asciidoc/appinfo/appinfo.adoc
src/main/java/site/dogether/appinfo/controller/AppInfoController.java
src/main/java/site/dogether/appinfo/controller/AppInfoExceptionHandler.java
src/main/java/site/dogether/appinfo/controller/response/AppInfoErrorCode.java
src/main/java/site/dogether/appinfo/controller/response/AppInfoSuccessCode.java
src/main/java/site/dogether/appinfo/controller/response/ForceUpdateCheckResponse.java
src/main/java/site/dogether/appinfo/service/AppInfoService.java
src/main/java/site/dogether/appinfo/service/exception/InvalidAppVersionException.java
src/test/java/site/dogether/appinfo/service/AppInfoServiceTest.java
src/test/java/site/dogether/docs/appinfo/AppInfoControllerDocsTest.java

Resolves #158 
- 앱 강제 업데이트 필요 여부 확인 API 구현
X

앱 강제 업데이트 필요 여부 확인 API 구현

---

.github/workflows/ci-cd.yml

Resolves #171
- github actions 배포 시 slack으로 알림 가도록 설정
X

github actions 배포 시 slack으로 알림 가도록 설정

---

.github/workflows/ci-cd.yml
src/main/resources/application-performance-test.yml

Resolves #186 
- CI/CD 불필요한 문장 제거
- performance-test ddl-auto 옵션 변경
X

CI/CD 불필요한 문장 제거 및 performance-test ddl-auto 옵션 변경

---

src/docs/asciidoc/memberactivity/member-activity-v1.adoc
src/test/java/site/dogether/docs/memberactivity/MemberActivityControllerV1DocsTest.java

Resolves #190
- API 문서 내 들어가는 쿼리 파라미터 수정
X

API 문서 내 들어가는 쿼리 파라미터 수정

---

src/docs/asciidoc/memberactivity/member-activity-v1.adoc

Resolves #190
- snippets 경로 수정
X

api 문서 snippets 경로 수정

---

src/test/java/site/dogether/docs/memberactivity/MemberActivityControllerV1DocsTest.java

Resolves #190
- api 문서 내 page 관련 설명 추가
X

api 문서 내 page 관련 설명 추가

---

build.gradle
src/main/java/site/dogether/common/p6spy/CustomP6SpySqlFormatter.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application-pt.yml
src/main/resources/application.yml
src/main/resources/logback/logback-dev.xml
src/main/resources/logback/logback-local.xml
src/main/resources/logback/logback-pt.xml

Resolves #204 
- 로컬 & 성능 테스트 서버에 Hibernate logging 설정 적용
X

Hibernate 쿼리 로깅 설정 적용
