dogether-project/dogether-backend

- src/main/java/site/dogether/auth/infrastructure/AppleClientSecret.java
- src/main/java/site/dogether/auth/infrastructure/AppleOAuthProvider.java
- src/main/java/site/dogether/auth/infrastructure/JwtHandler.java
- src/main/java/site/dogether/auth/infrastructure/client/apple/AppleApiClient.java
- src/main/java/site/dogether/auth/service/AuthService.java
- Apple Client Secret 생성 시 `Jwts.builder().header`에 들어갈 alg를 String으로 변경
- 가독성을 위한 개행, 네이밍 개선
- 예외 처리 필요한 부분 추가
- revoke의 성공 여부에 따라 회원 정보를 삭제하도록 개선
> [BE] 애플 로그인 revoke 요청이 실패하는 오류 수정

- src/main/java/site/dogether/auth/controller/AuthController.java
- src/main/java/site/dogether/auth/infrastructure/AppleOAuthProvider.java
- src/main/java/site/dogether/auth/infrastructure/JwtHandler.java
- src/main/java/site/dogether/auth/infrastructure/client/apple/AppleApiClient.java
- src/main/java/site/dogether/auth/service/AuthService.java
애플 refresh token 요청 시 발생하는 오류 수정을 위해 ErrorResponse를 매핑, 로깅을 추가합니다.
https://developer.apple.com/documentation/signinwithapplerestapi/errorresponse
> [BE] RT 요청 시 ErrorResponse 매핑, 로깅 추가

- src/main/java/site/dogether/notification/infrastructure/firebase/sender/SimpleFcmNotificationRequest.java
iOS팀 요청에 따라 Puth Notification 전송에 `Content-available` 옵션을 True로 설정
This closes #17
> [BE] Puth Notification Content Available 옵션 추가

- src/main/java/site/dogether/DogetherApplication.java
- src/main/java/site/dogether/challengegroup/entity/ChallengeGroup.java
- src/main/java/site/dogether/challengegroup/entity/ChallengeGroupDurationOption.java
- src/main/java/site/dogether/challengegroup/entity/ChallengeGroupStartAtOption.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/common/audit/entity/BaseEntity.java
- src/test/java/site/dogether/docs/dailytodo/DailyTodoControllerDocsTest.java
- 잘못 설정된 챌린지 그룹 테이블의 시작일, 종료일 컬럼 타입을 date로 정정함.
- 데이터 초기 저장시 updated_at에 값이 삽입되는 문제 해결
- 더이상 사용하지 않는 JPA Auditing 코드 제거
This closes #34
> [BE] 챌린지 그룹 테이블에 잘못된 컬럼 타입 수정 & updated_at 컬럼 잘못된 기본값 삽입 수정

- src/docs/asciidoc/dailytodo/daily-todo.adoc
- src/docs/asciidoc/dailytodocertification/daily-todo-certification.adoc
- src/main/java/site/dogether/dailytodo/controller/DailyTodoController.java
- src/main/java/site/dogether/dailytodo/controller/request/CertifyDailyTodoRequest.java
- src/main/java/site/dogether/dailytodo/controller/response/DailyTodoSuccessCode.java
- src/main/java/site/dogether/dailytodo/controller/response/GetChallengeMemberTodayTodosResponse.java
- src/main/java/site/dogether/dailytodo/service/DailyTodoService.java
- src/main/java/site/dogether/dailytodocertification/controller/DailyTodoCertificationController.java
- src/main/java/site/dogether/dailytodocertification/controller/request/CertifyDailyTodoRequest.java
- src/main/java/site/dogether/dailytodocertification/controller/response/DailyTodoCertificationResponse.java
- src/main/java/site/dogether/dailytodocertification/controller/response/GetDailyTodoCertificationByIdResponse.java
- src/main/java/site/dogether/dailytodocertification/service/DailyTodoCertificationService.java
- src/main/java/site/dogether/dailytodocertification/service/dto/DailyTodoCertificationDto.java
- src/test/java/site/dogether/docs/dailytodo/DailyTodoControllerDocsTest.java
- src/test/java/site/dogether/docs/dailytodocertification/DailyTodoCertificationControllerDocsTest.java
양성욱 담당 API 명세를 최신화하였다.
- 참여중인 특정 챌린지 그룹의 내 데일리 투두 전체 조회 API
- 어제 작성한 데일리 투두 내용 전체 조회 API
- 데일리 투두 생성 API
- 데일리 투두 인증 생성 API
- 검사해야할 데일리 투두 인증 목록 조회 API
- 데일리 투두 인증 검사 API
- 참여중인 특정 챌린지 그룹의 특정 그룹원이 당일 작성한 데일리 투두 전체 조회 API
- 푸시 알림 토큰 저장 API
- 푸시 알림 토큰 삭제 API
- S3 Presigned URL 발급 API
This closes #31
> [BE] 성욱님 담당 API 명세 최신화

- src/main/java/site/dogether/auth/service/AuthService.java
- src/main/java/site/dogether/challengegroup/repository/ChallengeGroupMemberRepository.java
- src/main/java/site/dogether/common/audit/entity/BaseEntity.java
- src/main/java/site/dogether/dailytodo/repository/DailyTodoRepository.java
- src/main/java/site/dogether/dailytodocertification/repository/DailyTodoCertificationRepository.java
- src/main/java/site/dogether/member/entity/Member.java
- src/main/java/site/dogether/member/service/MemberService.java
- src/main/java/site/dogether/member/service/MemberWithdrawService.java
- src/main/java/site/dogether/memberactivity/repository/DailyTodoStatsRepository.java
- src/main/java/site/dogether/notification/repository/NotificationTokenJpaRepository.java
- 회원 탈퇴 시 연관된 테이블의 is_deleted 컬럼을 true로 바꿉니다. 
- 연관 테이블 : 
`notification_token`, `challenge_group_member,` `daily_todo`, `daily_todo_stats`, `daily_todo_certificaiton`
- 논리 삭제된 회원이 재가입할 시 물리 삭제 후 새로 회원을 등록합니다.
- 물리 삭제는 회원의 자식 테이블을 모두 cascadeType을 remove 로 설정하여 삭제합니다.
- 회원 탈퇴 로직에서 MemberService가 다른 도메인을 모두 의존하기 때문에 순환참조 방지를 위해 MemberWithdrawService를 따로 둡니다.
> [BE] 회원 탈퇴 시 연관 데이터 논리 삭제 기능 구현

- src/docs/asciidoc/challengegroup/challenge-group.adoc
- src/docs/asciidoc/enum/challenge-group-status.adoc
- src/main/java/site/dogether/challengegroup/controller/ChallengeGroupController.java
- src/main/java/site/dogether/challengegroup/controller/response/JoinChallengeGroupResponse.java
- src/main/java/site/dogether/challengegroup/entity/ChallengeGroup.java
- src/main/java/site/dogether/challengegroup/entity/ChallengeGroupStatus.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/challengegroup/service/dto/JoinChallengeGroupDto.java
- src/main/java/site/dogether/challengegroup/service/dto/JoiningChallengeGroupDto.java
- src/test/java/site/dogether/docs/challengegroup/ChallengeGroupControllerDocsTest.java
- src/test/java/site/dogether/docs/challengegroup/enumtype/ChallengeGroupStatusDocs.java
- src/test/java/site/dogether/docs/util/CommonDocsController.java
- src/test/java/site/dogether/docs/util/CommonDocsControllerTest.java
- src/test/java/site/dogether/docs/util/DocumentLinkGenerator.java
- src/test/java/site/dogether/docs/util/EnumDocs.java
- 챌린지 그룹 상태 추가
- 종료일 당일의 상태를 표현하기 위해 ChallengeGroupStatus enum 필드에 D_DAY 상태 필드 추가
- RestDocs에 그룹 상태 enum docs 추가
- 챌린지 그룹 조회 API 응답 필드 수정
- 마지막 인증일일때 progressRate가 1.0이도록 로직 수정
- startAt 필드 추가
> [BE] 챌린지 그룹 종료일 상태 추가, 조회 응답 필드 변경

- src/docs/asciidoc/challengegroup/challenge-group.adoc
- src/docs/asciidoc/memberactivity/member-activity.adoc
- src/main/java/site/dogether/challengegroup/controller/ChallengeGroupController.java
- src/main/java/site/dogether/challengegroup/controller/response/ChallengeGroupMemberRankResponse.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/memberactivity/controller/MemberActivityController.java
- src/main/java/site/dogether/memberactivity/controller/response/GetGroupActivityStatResponse.java
- src/main/java/site/dogether/memberactivity/controller/response/GetMemberAllStatsResponse.java
- src/test/java/site/dogether/docs/challengegroup/ChallengeGroupControllerDocsTest.java
- src/test/java/site/dogether/docs/memberactivity/controller/MemberActivityControllerDocsTest.java
- 참여중인 특정 챌린지 그룹의 그룹원 전체 랭킹 조회 api
- 참여중인 특정 챌린지 그룹 활동 통계 조회 api
- 사용자의 활동 통계 및 작성한 인증 목록 전체 조회 api
클라이언트의 요구사항에 맞춰 문서 수정하였습니다.
- 참여중인 특정 챌린지 그룹의 그룹원 전체 랭킹 조회 api
- member Id값 추가
- 스토리 존재하는지 상태 여부 추가
- 참여중인 특정 챌린지 그룹 활동 통계 조회 api
- 초대코드 추가
- 그룹원 수(최대 그룹 참여 인원, 현재 참여중인 인원) 추가
- 사용자의 활동 통계 및 작성한 인증 목록 전체 조회 api
- 필터링 추가(투두 완료일 순, 그룹 생성일 순)
- 검사 대기, 인정, 노인정 필터링 추가
This closes #55
> [BE] 담당 API 명세 업데이트

- src/main/java/site/dogether/challengegroup/controller/ChallengeGroupController.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/dailytodohistory/entity/DailyTodoHistoryReadStatus.java
- src/main/java/site/dogether/dailytodohistory/exception/InvalidDailyTodoHistoryReadStatusException.java
- src/main/java/site/dogether/dailytodohistory/service/DailyTodoHistoryService.java
- src/test/java/site/dogether/docs/challengegroup/ChallengeGroupControllerDocsTest.java
- src/test/java/site/dogether/docs/util/EnumDocs.java
- 각 멤버별 히스토리 읽을 것이 남았는지 상태 포함
viewer 기준으로 랭킹을 조회하였을 때 같은 챌린지 그룹에 존재하는 멤버들의 히스토리를 읽었는지 안읽었는지 여부를 표시하도록 상태를 추가하였습니다.
This closes #43
> [BE] 참여중인 특정 챌린지 그룹의 그룹원 전체 랭킹 조회 API 수정

- src/main/java/site/dogether/memberactivity/controller/response/GetMemberAllStatsResponse.java
- src/main/java/site/dogether/memberactivity/service/MemberActivityService.java
- src/test/java/site/dogether/docs/memberactivity/controller/MemberActivityControllerDocsTest.java
사용자의 활동 통계 및 작성한 인증 목록 전체 조회 api 내 response 형식 수정
status에 따른 반환값을 기존에는 `dailyTodoCertifications`으로 처리했으나, status에 따라 다른 명칭으로 반환할 수 있도록 형식을 수정하였습니다.
투두 완료일 순 -> certificationsGroupedByTodoCompletedAt
그룹 생성일 순 -> certificationsGroupedByGroupCreatedAt
This closes #75
> [BE] 사용자의 활동 통계 및 작성한 인증 목록 전체 조회 api 명세 수정

- src/main/java/site/dogether/challengegroup/entity/ChallengeGroup.java
- src/test/java/site/dogether/challengegroup/entity/ChallengeGroupTest.java
**수정 전 : 마지막 수행일까지 증가**
예시) 5월 9일에 만든 3일짜리 오늘 시작 그룹인 경우
5.10일에 조회 - progressDay 2
5.11일(마지막 활동일)에 조회 → progressDay 3
5.12일(dday)에 조회 → progressDay 3
5.13일에 조회 → progressDay 3
**수정 후: 종료일(D_DAY)까지 증가**
5.10일에 조회 - progressDay 2
5.11일(마지막 활동일)에 조회 → progressDay 3
5.12일(dday)에 조회 → progressDay 4
5.13일에 조회 → progressDay 4
> [BE] 챌린지 그룹 진행일, 진행률 증가 기준 수정

- src/docs/asciidoc/challengegroup/challenge-group.adoc
- src/main/java/site/dogether/challengegroup/controller/ChallengeGroupController.java
- src/main/java/site/dogether/challengegroup/controller/response/ChallengeGroupSuccessCode.java
- src/main/java/site/dogether/challengegroup/controller/response/IsParticipatingChallengeGroupResponse.java
- src/main/java/site/dogether/challengegroup/controller/response/JoinChallengeGroupResponse.java
- src/main/java/site/dogether/challengegroup/entity/ChallengeGroup.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/challengegroup/service/dto/JoinChallengeGroupDto.java
- src/test/java/site/dogether/docs/challengegroup/ChallengeGroupControllerDocsTest.java
- 챌린지 그룹 참여 여부 조회 API를 추가합니다.
수정 전: 특정 페이지 분기를 위해 참여 여부만 필요한 상황인데 기존엔 전체 그룹 리스트 조회해서 참여 여부 판단함
수정 후: 챌린지 그룹 참여 여부 조회 API를 추가
추가 변경 사항
- 챌린지 그룹 참여 API 응답 필드에 duration 추가
> [BE] 챌린지 그룹 참여 여부 조회 API 추가

- src/main/java/site/dogether/member/entity/Member.java
잘못 설정된 사용자 프로필 이미지 설정을 정정하였습니다.
- S3 이미지 정리
- Member 도메인에 올바른 회원 프로필 이미지로 수정
- 기존 개발 서버 DB에 저장된 회원 이미지 정보를 올바른 이미지로 수동 변경
This closes #84
> [BE] 잘못 설정된 사용자 프로필 이미지 URL 정정

- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/dailytodo/entity/DailyTodo.java
- src/main/java/site/dogether/dailytodo/service/DailyTodoService.java
- src/main/java/site/dogether/dailytodocertification/service/DailyTodoCertificationService.java
- src/main/java/site/dogether/dailytodohistory/entity/DailyTodoHistoryRead.java
- src/main/java/site/dogether/memberactivity/entity/DailyTodoStats.java
- src/main/java/site/dogether/memberactivity/exception/DailyTodoStatsNotFoundException.java
- src/test/java/site/dogether/dailytodo/entity/DailyTodoTest.java
- src/test/java/site/dogether/dailytodo/service/DailyTodoServiceTest.java
- src/test/java/site/dogether/dailytodocertification/service/DailyTodoCertificationServiceTest.java
투두 검사로 인해 투두 상태가 변경될 때 사용자 별 데일리 투두 통계 값을 변경할 수 있도록 추가
- 사용자가 투두를 인증할 때 통계 값 변경 (certificated_count 값 증가)
- 투두를 누군가 검사할 때 사용자의 통계 값 변경 (certificated_count 값 감소, approved_count or rejected_count 증가)
This closes #83
> [BE] 투두 상태 변경 시 사용자 별 데일리 투두 통계 값 변경 기능 추가

- src/main/java/site/dogether/challengegroup/entity/ChallengeGroupMember.java
챌린지 그룹 중복 참여 오류를 수정합니다.
기존에도 서비스에서 그룹에 참여하려는 유저가 해당 그룹에 이미 속해있는지 검증은 존재했습니다.
하지만 일명 "따닥"과 같은 동시 요청이 들어오는 경우 애플리케이션 단의 선행 검증만으로 중복 삽입을 완벽히 막을 수 없습니다.
이런 상황에서는 두 요청이 동시에 exists 검사를 통과한 후,
각각 save를 시도하게 되면서 결과적으로 동일 유저가 같은 그룹에 중복 참여하는 문제가 발생합니다.
따라서 DB 차원에서 challenge_group_id와 member_id의 조합에 유니크 제약조건을 걸어
동시에 insert가 시도되더라도 하나는 DB에서 막히고 예외를 발생시킬 수 있도록 수정합니다.
> [BE] 챌린지 그룹 중복 참여 오류 수정

- src/main/java/site/dogether/member/entity/Member.java
- src/main/java/site/dogether/member/service/MemberService.java
- src/test/java/site/dogether/member/service/MemberServiceTest.java
- 탈퇴한 회원이 동일한 providerId로 재가입 시, 기존 회원을 삭제한 후 insert하는 로직에서 오류가 발생했습니다.
- JPA의 쓰기 지연으로 인해 먼저 수행되는 delete 쿼리가 insert보다 db에 늦게 나가면서 member의 name에 걸려있던 유니크 제약에 걸리는 것을 확인했습니다.
- 회원 삭제 후 flush를 호출해 delete 쿼리를 db에 즉시 반영하도록 수정했습니다.
- name의 유니크 제약을 삭제했습니다. (현재 애플에서 내려오는 사용자 이름을 name으로 사용하고 있는데 이는 같을 수 있으므로)
> [BE] 회원 재가입 시 발생하는 오류 수정

- src/main/java/site/dogether/challengegroup/entity/AchievementRateCalculator.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/dailytodo/entity/DailyTodos.java
기존에 데일리 투두들을 계산하는 로직을 dailyTodos를 활용하고자 하였는데 dailyTodos는 투두가 null일 경우 예외처리를 진행하고 있어, 투두가 없으면 투두들을 조회하지 못하는 문제 발생
지금 당장은 투두들을 계산하는 로직을 다른 곳으로 이동한 후 추후 다시 리팩토링 진행 예정
This closes #86
>  [BE] 그룹원 랭킹 계산 오류 해결

- src/main/java/site/dogether/dailytodo/entity/MyTodoSummary.java
- src/main/java/site/dogether/memberactivity/service/MemberActivityService.java
인정받은 투두만 인증된 투두로 카운팅되면서 문제 발생
인정, 노인정, 검사 대기 중인 투두들을 카운팅 할 수 있도록 수정
This closes #102
>  [BE] 참여중인 특정 챌린지 그룹 활동 통계 조회 api 로직 수정

- src/main/java/site/dogether/memberactivity/service/MemberActivityService.java
certificatedRate를 double 타입으로 계산할 수 있도록 수정
This closes #102
> [BE] 참여중인 특정 챌린지 그룹 활동 통계 조회 api 로직 수정

- src/docs/asciidoc/challengegroup/challenge-group.adoc
- src/main/java/site/dogether/challengegroup/controller/ChallengeGroupController.java
- src/main/java/site/dogether/challengegroup/controller/request/SaveLastSelectedChallengeGroupInfoRequest.java
- src/main/java/site/dogether/challengegroup/controller/response/ChallengeGroupSuccessCode.java
- src/main/java/site/dogether/challengegroup/controller/response/GetJoiningChallengeGroupsResponse.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/challengegroup/service/dto/JoiningChallengeGroupsWithLastSelectedGroupIndexDto.java
- src/main/java/site/dogether/dailytodo/controller/response/GetMyDailyTodosResponse.java
- src/main/java/site/dogether/dailytodo/entity/DailyTodo.java
- src/main/java/site/dogether/dailytodo/service/dto/DailyTodoAndDailyTodoCertificationDto.java
- src/main/java/site/dogether/dailytodocertification/controller/DailyTodoCertificationController.java
- src/main/java/site/dogether/dailytodocertification/controller/request/ReviewDailyTodoCertificationRequest.java
- src/main/java/site/dogether/dailytodocertification/service/DailyTodoCertificationService.java
- src/main/java/site/dogether/memberactivity/controller/response/GetMemberAllStatsResponse.java
- src/test/java/site/dogether/dailytodo/entity/DailyTodoTest.java
- src/test/java/site/dogether/docs/challengegroup/ChallengeGroupControllerDocsTest.java
- src/test/java/site/dogether/docs/dailytodo/DailyTodoControllerDocsTest.java
- src/test/java/site/dogether/docs/dailytodocertification/DailyTodoCertificationControllerDocsTest.java
- src/test/java/site/dogether/docs/memberactivity/controller/MemberActivityControllerDocsTest.java
투두 피드백 기능 & 가장 마지막에 선택한 그룹 id 조회 관련 API 명세를 최신화 하였습니다.
- 검사 피드백 기능 추가 관련 API 명세 수정
- 데일리 투두 수행 인증 검사 요청값 문서 수정
- 참여중인 특정 챌린지 그룹에서 내 데일리 투두 전체 조회 (투두 작성 날짜만 입력) 응답값 문서에 검사 결과 필드 반영
- 사용자의 활동 통계 및 작성한 인증 목록 전체 조회 (투두 완료일 순) 응답값 문서에 검사 결과 필드 반영
- 사용자의 활동 통계 및 작성한 인증 목록 전체 조회 (그룹 생성일 순) 응답값 문서에 검사 결과 필드 반영
- 가장 마지막에 선택한 챌린지 그룹 id조회 기능 추가 관련 API 명세 수정
- 가장 마지막에 선택한 챌린지 그룹 id저장 API 문서 생성
- 참여중인 챌린지 그룹 정보 전체 조회 응답값 문서에 검사 결과 필드 반영
This closes #114
> 투두 피드백 기능 & 가장 마지막에 선택한 그룹 id 조회 관련 API 명세 최신화

- src/main/java/site/dogether/challengegroup/controller/ChallengeGroupController.java
- src/main/java/site/dogether/challengegroup/controller/response/GetJoiningChallengeGroupsResponse.java
- src/main/java/site/dogether/challengegroup/entity/LastSelectedChallengeGroupRecord.java
- src/main/java/site/dogether/challengegroup/repository/LastSelectedChallengeGroupRecordRepository.java
- src/main/java/site/dogether/challengegroup/service/ChallengeGroupService.java
- src/main/java/site/dogether/challengegroup/service/dto/JoiningChallengeGroupsWithLastSelectedGroupIndexDto.java
- src/main/java/site/dogether/dailytodo/controller/response/GetMyDailyTodosResponse.java
- src/main/java/site/dogether/dailytodo/entity/DailyTodo.java
- src/main/java/site/dogether/dailytodo/service/dto/DailyTodoAndDailyTodoCertificationDto.java
- src/main/java/site/dogether/dailytodocertification/exception/InvalidDailyTodoRejectReasonException.java
- src/main/java/site/dogether/memberactivity/service/MemberActivityService.java
- src/test/java/site/dogether/dailytodo/entity/DailyTodoTest.java
- src/test/java/site/dogether/dailytodo/service/DailyTodoServiceTest.java
- src/test/java/site/dogether/dailytodocertification/entity/DailyTodoCertificationTest.java
- src/test/java/site/dogether/dailytodocertification/service/DailyTodoCertificationServiceTest.java
투두 인증 검사 피드백 & 사용자가 가장 마지막에 선택한 그룹의 정보 저장 기능을 구현하였습니다. 마지막 선택 그룹 기능은 무언가 예외 상황이 발생할 때 에러를 보내는것 보다는 첫 번째 그룹 인덱스를 저장하고 보내는게 안정적이라 생각해 이 방식으로 구현하였습니다.
배포는 해당 PR 머지시 바로 진행하지 않고 테이블이 변경되는 다른 작업을 끝낸 후 함께 일괄 배포하겠습니다.
This closes #118
> 투두 인증 검사 피드백 & 사용자가 가장 마지막에 선택한 그룹의 정보 저장 기능 구현

- src/main/java/site/dogether/dailytodo/controller/DailyTodoController.java
- src/main/java/site/dogether/dailytodo/entity/DailyTodo.java
- src/main/java/site/dogether/dailytodo/service/DailyTodoService.java
- src/main/java/site/dogether/dailytodocertification/service/DailyTodoCertificationService.java
- src/main/java/site/dogether/dailytodohistory/entity/DailyTodoHistory.java
- src/main/java/site/dogether/dailytodohistory/repository/DailyTodoHistoryReadRepository.java
- src/main/java/site/dogether/dailytodohistory/repository/DailyTodoHistoryRepository.java
- src/main/java/site/dogether/dailytodohistory/service/DailyTodoHistoryService.java
- src/main/java/site/dogether/dailytodohistory/service/dto/TodoHistoryDto.java
- src/main/java/site/dogether/member/entity/Member.java
- src/test/java/site/dogether/dailytodo/service/DailyTodoServiceTest.java
- src/test/java/site/dogether/dailytodocertification/service/DailyTodoCertificationServiceTest.java
- src/test/java/site/dogether/docs/dailytodo/DailyTodoControllerDocsTest.java
투두 히스토리 저장 & 조회 방식을 개선하고 오늘보다 과거 날짜 투두의 히스토리가 보이는 문제를 해결하였습니다.
해당 PR도 바로 배포하지 않고 이후 진행할 오류 조치 완료후 함께 배포하겠습니다.
This closes #108
> 투두 히스토리 저장 & 조회 방식 개선 및 오늘보다 과거 날짜 투두의 히스토리가 보이는 문제 해결

- src/main/java/site/dogether/dailytodo/entity/DailyTodo.java
- src/main/java/site/dogether/developer_test/member/DeveloperTestMemberApi.java
- src/main/java/site/dogether/member/entity/Member.java
- 회원 탈퇴가 되지 않는 이슈를 해결하고 인정 피드백 입력에 대한 제약 조건을 null or 공백 허용으로 변경하였습니다. 
- 추가로 기존 양방향 매핑 코드는 StackOverFlow를 유발할 수 있는 잠재적 위험이 존재해 이를 방지하는 코드를 추가하였습니다.
그리고 현재는 회원 탈퇴시 관련 데이터를 모두 삭제하는 방식으로 JPA의 cascade 방식을 사용하지만 양방향 매핑을 해야하는 트레이드 오프가 존재하므로 더 나은 방법이 없는지 백엔드 회의를 진행할 필요가 있습니다. (@yeong0jae @Hwangseoeun )
This closes #123
> 회원 탈퇴가 작동되지 않는 이슈 해결 & 인정 피드백은 null과 공백이 허용되도록 변경

- src/main/java/site/dogether/challengegroup/entity/AchievementRateCalculator.java
- src/main/java/site/dogether/dailytodocertification/repository/DailyTodoCertificationCount.java
- src/main/java/site/dogether/memberactivity/service/MemberActivityService.java
- 데일리 투두 통계 페이지 에러
- 챌린지 그룹 랭킹 페이지 에러
위 에러 모두 투두 인증 카운트 객체의 NPE 문제로 인해 발생하였음을 확인했기에 조치했습니다.
> 투두 인증 카운트 NPE 문제 해결

- src/test/java/site/dogether/dailyTodoHistory/service/DailyTodoHistoryServiceTest.java
Resolves #142 
- 챌린지 그룹에 속한 그룹원의 당일 데일리 투두 히스토리 전체 조회 테스트를 추가합니다.
X
> [BE] 챌린지 그룹에 속한 그룹원의 당일 데일리 투두 히스토리 전체 조회 테스트 추가

- src/test/java/site/dogether/dailyTodoHistory/service/DailyTodoHistoryServiceTest.java
- src/test/java/site/dogether/docs/dailytodo/DailyTodoControllerDocsTest.java
Resolves #142 
- 다른 그룹원의 히스토리에서 피드백을 조회할 수 있음에 따라 REST Docs 문서를 수정합니다.
-  status가 REVIEW_PENDING일 경우 reviewFeedback을 null로 응답합니다.
X
> [BE] 다른 그룹원의 히스토리에서 피드백을 조회할 수 있음에 따라 REST Docs 문서 수정

- src/main/java/site/dogether/dailytodocertification/service/DailyTodoCertificationService.java
Resolves #155
- 특수 문자가 들어가더라도 문제가 발생하지 않도록 수정
X
> 투두 내용에 특수문자가 들어갈 경우 인증이 안되는 문제 해결

- .github/workflows/ci-cd.yml
Resolves #171
- github actions 배포 시 slack으로 알림 가도록 설정
X
> github actions 배포 시 slack으로 알림 가도록 설정

- src/main/java/site/dogether/dailytodo/repository/DailyTodoRepository.java
- src/main/java/site/dogether/dailytodo/service/DailyTodoService.java
#180
- 미인증 투두 조회시 투두 작성일 기준 내린차순 정렬로 반환되도록 로직 수정
기능이 UI적으로 잘 작동하는지 개발 서버에 배포 테스트 후 잘 작동하면 그대로 이슈 종료합니다.
> 투두 중간 추가시 나중에 추가된 투두가 위로 배치되도록 정렬 기능 변경
